
Config.NotificationText = {
    ["MISSION_COMPLETED"] = {
        text = 'Battlepass mission completed',
        type = 'success',

    },
    ["PREMIUM_ITEM"] = {
        text = 'This is a premium item',
        type = 'error',
    },
    ["CLAIMED_VEHICLE"] = {
        text = 'Claimed %s',
        type = 'success',
    },
    ["CLAIMED_ITEM"] = {
        text = 'Claimed %sx %s',
        type = 'success',
    },
    ["CLAIMED_CASH"] = {
        text = 'Claimed $%s cash',
        type = 'success',
    },
    ["NOT_ENOUGH_BP_LEVEL"] = {
        text = "You don't have enough BP level to claim this item!",
        type = 'error',
    },
    ["ALREADY_CLAIMED_BP_ITEM"] = {
        text = "You have already claimed this item!",
        type = 'error',

    },
    ["SELECT_BP_ITEM"] = {
        text = "Select BP item first to claim!",
        type = 'error',

    },
    ["PURCHASED_BATTLEPASS"] = {
        text = 'Successfully purchased battlepass',
        type = 'success',
    },
    ["ALREADY_PURCHASED"] = {
        text = "You already purchased the battlepass or it's already free",
        type = 'error',
    },
    ["WRONG_TBX_ID"] = {
        text = "This tebex is invalid!",
        type = 'error',
    },
    ["NOT_ENOUGH_MONEY"] = {
        text = "You don't have enough money!",
        type = 'error',
    },
    ["BOUGH_ITEM"] = {
        text = "Bought %s %s",
        type = 'success',
    },
    ["KEYBIND_DELETED"] = {
        text = "Keybind is succesfully deleted.",
        type = 'success',
    },
    ["CANT_DELETE_KEYBIND"] = {
        text = "You can't delete a system keybind!",
        type = 'error',
    },
    ["COMMAND_DELETED"] = {
        text = "Command is succesfully deleted.",
        type = 'success',
    },
    ["CANT_DELETE_COMMAND"] = {
        text = "You can't delete a system command!",
        type = 'error',
    },
    ["GUIDE_EMPTY"] = {
        text = "Guide content or name is empty!",
        type = 'error',
    },
}



Config.UILocales = {
    guidebook = 'Guidebook',
    battlepass = 'Battlepass',
    dailyrewards = 'Daily Rewards',
    store = 'Store',
    pausemenu = 'PAUSEMENU',
    exit_pausemenu = 'Exit From <br>Pausemenu',
    dailyrewards_text = 'Daily<br>Rewards',
    click_to_display = 'Click to display your daily rewards!',
    exit = 'QUIT GAME',
    map = 'MAP',
    store = 'STORE',
    hot_deals = 'HOT DEALS',
    hot_deal = 'HOT DEAL',
    settings = 'SETTINGS',
    guidebook = 'GUIDEBOOK',
    battlepass_menu = 'BATTLEPASS',
    characters = 'CHARACTERS',
    online_players = 'Online Players',
    cash = 'CASH',
    bank = 'BANK',
    battlepass_missions = 'Battlepass<br>Missions',
    complete_mission = 'Complete mission to get',
    click_to_display_store = 'Click to display deals on the store',
    resume = 'RESUME',
    made_payment = 'Made the payment ? <br> Unlock your battlepass now!',
    unlock_battlepass = 'UNLOCK <br>BATTLEPASS',
    tbx_id = 'Your payment tbx-id...',
    provide_tbx_id = 'Provide a tbx-id...',
    get_battlepass = "Get battlepass from store!",
    go_back = "Go Back",
    level = "Level",
    claim_free_battlepass = "Claim your battlepass reward!",
    claim = 'CLAIM!',
    premium = 'PREMIUM',
    free = 'FREE',
    day_remained = 'day remained',
    progression = 'Progression',
    get_battlepass_now = 'Get Battlepass <br>Now!',
    remained = 'hr remained',
    day = 'DAY',
    claim_daily_reward = 'Claim your daily reward!',
    claimed = "CLAIMED!",
    expired = "EXPIRED!",
    welcome = "Welcome To mRP’s Guidebook",
    general = "General",
    keybinds = "Keybinds",
    commands = "Commands",
    jobs = "Jobs",
    need_extra_help = "Need an extra help ?",

    get_support = "Get support from our discord server.",
    creating_new_guide = "Creating New Guide",
    create_new_guide = "Create New Guide",
    guide_name = "Guide Name",
    upload_photo = "Upload Photo",
    by_link = "by Link and youtube video",
    url = "URL...",
    upload = "Upload",
    create_guide = "Create Guide",
    click_on_command = "Click on any command to display it function.",
    search_command = "Search any command...",
    keybinds = "Keybinds", 
    cancel = "Cancel",
    create = "Create",
    command_desc = "Command description...",
    enter_command = "Enter command",
    save_guide = "Save Guide",
    edit_guide = "Edit Guidebook",
    del_command = "Delete command",
    create_new_command_info = "Create New Command Information",
    delete_keybind = "Delete Keybind Info",
    save_keybind = "Save Keybind Info",
    create_keybind = "Create Keybind Info",
    click_to_key_to_create_keybind = "Click keys to create new keybind information.",
    press_any_key_to_create_keybind = "Press on any key to create keybinds.",
    enter_keybind_desc = "Enter the keybind description.",
    click_to_create_combination = "Click<br>Another<br>Key To Create<br>Combination",
    enter_single_keybind_desc = "Enter single keybind description. ",
    default = "Default",
    enter_combination_keybind_desc = "Enter combination keybind description.",
    with = "With",
    press_any_key_to_display_keybind = "Press on any key to display keybinds.",
    no_combination = "No key <br>combination",
    select_key_to_create = 'Select a key to create info.',
    type_a_desc = "Type a description for the main key.",
    type_a_desc_for_combination ='Type a description for the combination key.',
    type_command_name ="You have to type name of the command",
    type_command_desc ="You have to type descripton of the command",

    are_you_sure_to_buy = "Are you sure to <br>buy this ITEM?",
    buy = "Buy",
    main = "MAIN",
    search_anything = "Search anything on store",
    buy_now = "Buy Now",
    change = "CHANGE",
    original = "ORIGINAL",
    inspect = "INSPECT", 
    are_you_sure_to_exit = "Are you sure to exit game?", 
    confirm = "Confirm", 
    are_you_sure_to_delete = "Are you sure to delete?"

}