fx_version 'cerulean'
version '5.0'
game 'gta5'

ui_page 'html/index.html'

data_file 'DLC_ITYP_REQUEST' 'stream/scrlt_ipif14max.ytyp'

shared_scripts {
	'configs/main_config.lua',
	'configs/get_framework_config.lua',
}

client_scripts {
    'configs/main_config.lua',
    'mainSystem/client/client.lua',
    'mainSystem/client/lapRaces.lua',
    'mainSystem/client/videoCallclient.lua',
    'configs/client_config.lua',
    'configs/custom_apps_callbacks.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'configs/main_config.lua',
    'mainSystem/server/server.lua',
    'configs/server_config.lua',
    'mainSystem/server/videoCallserver.lua'
}

files {
    "module/*.js",
    "module/animation/tracks/*.js",
    "module/animation/*.js",
    "module/audio/*js",
    "module/cameras/*.js",
    "module/core/*.js",
    "module/extras/core/*.js",
    "module/extras/curves/*.js",
    "module/extras/objects/*.js",
    "module/extras/*.js",
    "module/geometries/*.js",
    "module/helpers/*.js",
    "module/lights/*.js",
    "module/loaders/*.js",
    "module/materials/*.js",
    "module/math/interpolants/*.js",
    "module/math/*.js",
    "module/objects/*.js",
    "module/renderers/shaders/*.js",
    "module/renderers/shaders/ShaderChunk/*.js",
    "module/renderers/shaders/ShaderLib/*.js",
    "module/renderers/webgl/*.js",
    --"module/renderers/webxr/*.js",
    "module/renderers/webvr/*.js",
    "module/renderers/*.js",
    "module/scenes/*.js",
    "module/textures/*.js",
    "script.js",

    'html/*.html',
    'html/css/*.css',
    'html/css/fonts/Screenlock/*.otf',
    'html/css/fonts/*.otf',
    'html/css/fonts/*.ttf',
    'html/js/*.js',
    'html/img/*.png',
    'html/img/*.jpg',
    'html/img/ubereats/*.png',
    'html/img/mdt/*.png',
    'html/img/frames/*.png',
    'html/img/whatsapp/*.png',
    'html/img/ubereats/*.jpg',
    'html/img/olx/*.png',
    'html/img/definicoes/*.png',
    'html/img/definicoes/*.jpg',
    'html/img/twitter/*.png',
    'html/img/twitter/*.jpg',
    'html/img/memoji/*.png',
    'html/img/*.gif',
    'html/img/apps/*.png',
    'html/img/apps/*.jpg',
    'html/img/appsimessage/*.png',
    --'html/img/items/*.png',
    --'html/css/img/backgrounds/*.jpg',
    'html/css/img/welcome/*.png',
    'html/css/img/gps/*.jpg',
    'html/css/img/gps/*.svg',
    'html/css/img/welcome/*.jpg',
    'html/css/img/camera/*.jpg',
    'html/css/img/houses/*.jpg',
    'html/css/img/tempo/*.jpg',
    'html/css/img/appstore/*.jpg',
    'html/img/camera/*.jpg',
    'html/img/bateria/*.jpg',
    'html/img/safari/*.png',
    'html/img/safari/*.jpg',
    'html/img/backgrounds/*.jpg',
    'html/img/tiktok/*.png',
    'html/img/tiktok/*.jpg',
    'html/img/sistema/*.gif',
    'html/img/sistema/*.png',
    'html/img/sistema/*.jpg',
    'html/sounds/*.mp3',
    'html/css/img/wallet/*.png',
    'html/img/tinder/*.png',
    'html/img/tinder/*.jpg',
    'html/sounds/toques/*.mp3',
    'html/sounds/notif/*.mp3',
    'html/sounds/alarm/*.mp3',
    'html/sounds/misc/*.mp3',
    'html/img/appstore/*.jpg',
}

lua54 'yes'

escrow_ignore {
	'configs/main_config.lua',
    'mainSystem/client/lapRaces.lua',
    'configs/server_config.lua',
    'configs/get_framework_config.lua',
    'configs/custom_apps_callbacks.lua',
    'configs/client_config.lua',
}

preloads {
    'html/*.html',
    'html/css/*.css',
    'html/css/fonts/*.otf',
    'html/css/fonts/*.ttf',
    'html/js/*.js',
    'html/img/frames/*.png',
    'html/img/*.png',
    'html/img/*.jpg',
    'html/css/fonts/Screenlock/*.otf',
    'html/img/memoji/*.png',
    'html/img/*.gif',
    'html/img/apps/*.png',
    'html/img/olx/*.png',
    'html/img/definicoes/*.jpg',
    'html/img/mdt/*.png',
    'html/img/definicoes/*.png',
    'html/img/camera/*.png',
    'html/img/apps/*.jpg',
    'html/img/appsimessage/*.png',
    'html/img/backgrounds/*.jpg',
    'html/img/twitter/*.png',
    'html/img/twitter/*.jpg',
    'html/img/items/*.png',
    --'html/css/img/backgrounds/*.jpg',
    --'html/img/ubereats/*.png',
    'html/img/whatsapp/*.png',
    'html/img/tiktok/*.png',
    'html/img/tiktok/*.jpg',
    'html/img/tinder/*.png',
    'html/img/tinder/*.jpg',
    'html/img/ubereats/*.jpg',
    'html/img/safari/*.png',
    'html/img/safari/*.jpg',
    'html/css/img/welcome/*.png',
    'html/css/img/gps/*.jpg',
    'html/css/img/gps/*.svg',
    'html/css/img/wallet/*.png',
    'html/img/bateria/*.jpg',
    'html/css/img/welcome/*.jpg',
    'html/css/img/camera/*.jpg',
    'html/img/sistema/*.gif',
    'html/img/sistema/*.png',
    'html/img/sistema/*.jpg',
    'html/css/img/tempo/*.jpg',
    'html/css/img/appstore/*.jpg',
    'html/sounds/*.mp3',
    'html/sounds/toques/*.mp3',
    'html/img/appstore/*.jpg',
    'html/sounds/notif/*.mp3',
    'html/sounds/alarm/*.mp3',
    'html/sounds/misc/*.mp3',
}

exports {
    'isPhoneOpen',
    'sendiMessage',
    'sendWhatsapp',
    'getPhoneNumber',
    'closePhone',
    'openPhone',
    'isCamaraOpen',
}
dependency '/assetpacks'