name: ci
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 🔄 Synchronizing files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./server/
          server-dir: ./server/

  rcon:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🔂 Restarting server
        uses: Plagiatus/RCON-Action@v0.2
        with:
          server: ${{ secrets.FIVEM_RCON_HOST }}
          port: ${{ secrets.FIVEM_RCON_PORT }}
          password: ${{ secrets.FTP_PASSWORD }}
          commands: '["restart"]'
